### ISSUE TITLE
"Occamy.C" trojan appearing on every release except for the first one

### ISSUE THREAD

**Issue by CubicRalsei** [CloneTrooper1019/Roblox-Studio-Mod-Manager#58] opened 2020-04-13 23:29 UTC
title

**Comment by CloneTrooper1019** [comment] 2020-04-16 03:32
Duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

**Comment by CloneTrooper1019** [comment] 2020-04-16 03:33
Make sure your Windows Defender definitions are up to date:
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

**Closed by CloneTrooper1019** 2020-04-16 03:32 UTC
