### ISSUE TITLE
RSMM will no longer startup

### ISSUE THREAD

**Issue by Sparkypen7** [CloneTrooper1019/Roblox-Studio-Mod-Manager#56] opened 2020-04-08 21:17 UTC
Whenever I try to start up RSMM, Windows automatically blocks the process as it states:

"Operation did not complete successfully because the file contains a virus or potentially unwanted software."

I've been using RSMM for several years now without any issue, but all the sudden Windows is no longer allowing me to use it at all because it thinks it has a virus inside of it.

I've read the source code several times and there are no signs that RSMM has any virus inside of it.

Similarly, looking at the other issues that have been recently posted, it seems like other people are having virus detection software flag it as a virus, but are still able to use the software. 

For my case, I am unable to run RSMM entirely. Disabling Windows Defender is not a feasible option for me.

**Comment by CloneTrooper1019** [comment] 2020-04-09 01:27
Duplicate of this issue:
https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

I'll be looking into this soon.

**Closed by CloneTrooper1019** 2020-04-09 01:27 UTC
