### ISSUE TITLE
Windows Defender false positives

### ISSUE THREAD

**Issue by Frenzyy-1** [CloneTrooper1019/Roblox-Studio-Mod-Manager#85] opened 2021-03-10 18:21 UTC
![image](https://user-images.githubusercontent.com/72508034/110677708-6e817e80-8210-11eb-957e-755777e1a695.png)

**Comment by CloneTrooper1019** [comment] 2021-03-10 23:08
Duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

**Closed by CloneTrooper1019** 2021-03-10 23:08 UTC
