### ISSUE TITLE
Plugins do not install

### ISSUE THREAD

**Issue by LouieK22** [CloneTrooper1019/Roblox-Studio-Mod-Manager#57] opened 2020-04-13 15:03 UTC
When installing a plugin through the site, it won't install. However, running studio from the CLI with the correct arguments (e.g. ``.\RobloxStudioBeta.exe -task InstallPlugin -pluginId 1997686364`` still installs the plugin just fine.

**Comment by Hexcede** [comment] 2020-04-16 17:18
This is due to how Roblox launches. RobloxStudioModManager essentially acts as the Roblox launcher, and based on a brief look at the code, the protocol changed, or RSMM doesn't support it. It does this because the normal Roblox launcher forces an install at its own folder, and RSMM has its own install functionality and install location.

The solution would need to be (re)implementing the plugin protocol.

**Comment by CloneTrooper1019** [comment] 2020-05-01 09:38
I’m going to treat this as a duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/50 for now, as I still need to get this issue addressed.

**Closed by CloneTrooper1019** 2020-05-01 09:38 UTC
