### ISSUE TITLE
High false positive count on VT

### ISSUE THREAD

**Issue by nooneisback** [CloneTrooper1019/Roblox-Studio-Mod-Manager#63] opened 2020-05-29 21:10 UTC
This link says it all.
https://www.virustotal.com/gui/file/2057cd867350fb5925de3c378012268ac69c3d4959ba50b5130bacd4a5b9e11e/detection

This is the newest version I scanned and it took me about 10 minutes of wrestling with Bitdefender to actually open it. Also, it is impossible to complete the installation without disabling protection.

**Comment by CloneTrooper1019** [comment] 2020-05-31 05:28
Duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54
Looks like I need to get this resubmitted for analysis again 😔

**Closed by CloneTrooper1019** 2020-05-31 05:28 UTC
