### ISSUE TITLE
Infected Files

### ISSUE THREAD

**Issue by Kolinchkov** [CloneTrooper1019/Roblox-Studio-Mod-Manager#64] opened 2020-06-07 05:00 UTC
The two files (folder/.exe) contain Win32:Adware-gen according to my anti-virus. Suggested actions, please? I thank the reponder(s) in advance!

**Comment by CloneTrooper1019** [comment] 2020-06-07 06:44
Duplicate of https://github.com/CloneTrooper1019/Roblox-Studio-Mod-Manager/issues/54

**Closed by CloneTrooper1019** 2020-06-07 06:44 UTC
